### ISSUE TITLE
Problem encountered in reproduction

### ISSUE THREAD

**Issue by googol116** [anonymspro/PFIRec#1]
With the code you provided and the python library provided in requirements-lock.txt, I reproduced the whole project, emperical.py runs perfectly, but model.py runs with problems, I put the results of the model.py run in the attachment, could you please help me to see why there is a problem? 
[model_results.txt](https://github.com/mcxwx123/PFIRec/files/13596556/model_results.txt)

**Comment by mcxwx123** [comment]
Sorry for the late reply. The reason for this warning in the logistic regression model is that it doesn't fit the data well (it performs the worst among all baseline models). I have tried increasing the number of iterations, but it didn't help much. It's normal for this warning to appear, and you can simply ignore it or comment out the logistic regression model; it won't affect the results of other models.
